name: Code Quality

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Install the latest version of uv and set the python version
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        make install

    - name: Run pre-commit hooks
      run: |
        uvx pre-commit run --all-files

    - name: Run Ruff
      run: |
        make format lint

    - name: Run MyPy
      run: |
        make type-check

    - name: Run Bandit
      run: |
        make security-check

    - name: Run Tests
      run: |
        make test
